WCSCoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCSCoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:


        pilot:
            type: string
            length: 255
        freeSeats:
            type: integer
        takeofTime:
            type: datetime
        title:
            type: string
            lenght: 1
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCSCoavBundle\Entity\Terrain
            inversedBy: departures
        arrival:
            targetEntity: WCSCoavBundle\Entity\Terrain
            inversedBy: arrivals
        planemodel :
            targetEntity: WCSCoavBundle\Entity\PlaneModel
            inversedBy: planemodel

    oneToMany:
         flight :
            targetEntity: WCSCoavBundle\Entity\Flight
            mappedBy: flight

